<?php
/* Header for qincai homepage */
function io_header(){ if (is_bookmark()) return; io_loading_fx(); io_show_header(); io_show_mobile_header(); do_action('io_content_header_after_code', get_queried_object_id()); }
function io_loading_fx(){ if (io_is_spider()) return; if (io_get_option('loading_fx', false)) { echo '<div id="loading_fx">'; loading_type(); echo '<script type="text/javascript"> document.addEventListener("DOMContentLoaded",()=>{const loader=document.querySelector("#loading_fx");if(loader){loader.classList.add("close");setTimeout(()=>loader.remove(),600)}}); </script>'; echo '</div>'; } }
function io_qincai_header_menu_items(){ return array(array('label'=>'AI 工具','href'=>'#module_id_1'),array('label'=>'AI大模型','href'=>'#module_id_2'),array('label'=>'AI云端部署','href'=>'#module_id_3'),array('label'=>'AI教程资源','href'=>'#module_id_4'),array('label'=>'AI资讯','href'=>'#module_id_5'),array('label'=>'Claw生态','href'=>'#module_id_6')); }
function io_qincai_render_main_nav(){ $items = io_qincai_header_menu_items(); echo '<div class="qincai-navbar-header-menu d-none d-md-flex"><ul class="nav navbar-header qincai-navbar-header mr-3">'; foreach ($items as $item) { echo '<li class="menu-item"><a href="' . esc_url($item['href']) . '">' . esc_html($item['label']) . '</a></li>'; } echo '</ul></div>'; }
function io_show_header(){ echo '<header class="main-header header-fixed qincai-header"><div class="header-nav blur-bg"><nav class="switch-container container-header nav-top qincai-nav-top d-flex align-items-center h-100' . get_page_mode_class() . '" style="height:64px;padding:0 24px;max-width:1280px;margin:0 auto;">'; echo '<div class="navbar-logo d-flex mr-4 qincai-navbar-logo" style="flex:0 0 auto;max-width:180px;">' . io_get_logo_html() . '</div>'; io_qincai_render_main_nav(); echo '<div class="flex-fill qincai-header-fill"></div><ul class="nav header-tools position-relative qincai-header-tools"><li class="header-icon-btn nav-search"><a href="javascript:" class="search-ico-btn nav-search-icon" data-toggle-div data-target="#search-modal" data-z-index="101"><i class="search-bar"></i></a></li></ul><div class="d-block d-md-none menu-btn" data-toggle-div data-target=".mobile-nav" data-class="is-mobile" aria-expanded="false"><span class="menu-bar"></span><span class="menu-bar"></span><span class="menu-bar"></span></div></nav></div></header>'; }
function io_show_mobile_header(){ $html = '<div class="mobile-header"><nav class="mobile-nav"><ul class="menu-nav mb-4">'; $html .= io_nav_menu('mobile_menu', false); $html .= '</ul>'; $html .= io_get_menu_user_box('mb-4'); $html .= '</nav></div>'; echo $html; }
function io_get_logo_html($h1 = false){ $logo_light = io_get_option('logo_normal_light', ''); $logo_dark = io_get_option('logo_normal', ''); $blog_name = get_bloginfo('name'); $is_home = (is_home() || is_front_page() || is_mininav()); $html=''; if ($is_home || $h1) { $html .= '<h1 class="text-hide position-absolute">' . $blog_name . '</h1>'; } $html .= '<a href="' . esc_url(home_url()) . '" class="logo-expanded">'; if (theme_mode() == 'io-black-mode') { $html .= '<img src="' . $logo_dark . '" height="36" switch-src="' . $logo_light . '" is-dark="true" alt="' . $blog_name . '">'; } else { $html .= '<img src="' . $logo_light . '" height="36" switch-src="' . $logo_dark . '" is-dark="false" alt="' . $blog_name . '">'; } $html .= '</a>'; return $html; }
function io_get_head_content(){ io_auto_theme_mode(); io_custom_theme_css(); echo io_get_option('code_2_header',''); }
add_action('wp_head','io_get_head_content');
function io_auto_theme_mode(){ if(get_query_var('bookmark_id')) return ''; $auto_mode = io_get_option('theme_auto_mode', 'manual-theme'); if ($auto_mode=='auto-system' || (defined( 'WP_CACHE' ) && WP_CACHE && $auto_mode!='null')) { $ars = ''; if($auto_mode=='auto-system') $ars = ' || (!__night && window.matchMedia("(prefers-color-scheme: dark)").matches)'; echo '<script>var __default_c = "'. io_get_option('theme_mode','') .'";var __night = document.cookie.replace(/(?:(?:^|.*;\s*)io_night_mode\s*\=\s*([^;]*).*$)|^.*$/, "$1");try {if (__night === "0"'.$ars.') {document.documentElement.classList.add("io-black-mode");}} catch (_) {}</script>'; } }
function io_custom_theme_css() { $root=''; $color = io_get_option('theme_color', ''); if (!empty($color)) { $rgb = extractRGB($color); $root .= '--theme-color:' . $color . ';'; $root .= '--theme-color-rgb:' . $rgb['r'] . ',' . $rgb['g'] . ',' . $rgb['b'] . ';'; $root .= '--hover-color:' . get_color_deepen($color) . ';'; $root .= '--focus-shadow-color:' . set_color_opacity(get_color_deepen($color), 0.6) . ';'; } $css=''; if (!empty($root)) { $css .= ':root{' . $root . '}'; } if (io_get_option("custom_css", '')) { $css .= substr(io_get_option("custom_css", ''), 0); } echo "<style>" . $css . "</style>"; }
